menu:
  Index:
    url: /
    External: false
    name: 首页
  Tags:
    url: /tags
    External: false
    name: 标签
#  Categories:
#    url: /categories
#    External: false
#    name: 分类
  Archives:
    url: /archives
    External: false
    name: 归档
  About:
    url: /about
    External: false
    name: 关于

# 联系方式
contact:
  github: "https://github.com/rainlogs"
  twitter:
  weibo:
  zhihu:
  facebook:

# 是否显示封面图片
showFeatureImage: true

# 首页头像图片
avatar: https://s1.ax1x.com/2022/07/12/j2nnE9.png

# 谷歌统计 跟踪 ID
ga:

# Gittalk 评论组件
# See: https://github.com/gitalk/gitalk/
gitalk:
  enable: false
  clientId: "691034a26efb56f32631"
  clientSecret: "45f8b7ae31b947165691c8cf89e365ed49a0954a"
  repository: hexo
  owner: rainlogs
  createIssueManually: true

# 是否使用 bootcdn
use_bootcdn: false

# 底部链接
bottom_link:
  rss:
    url:
    text: RSS
    class: rss
  icp:
    url: # beian.miit.gov.cn
    text: # XICP备 00000000号-0
    class: icp

# 底部显示来源信息
bottom_source:
  enable: true
